---
- hosts: backup
  become: true

  vars_files:
    - config.yml

  pre_tasks:
    - name: Download and install gickup.
      ansible.builtin.unarchive:
        src: https://github.com/cooperspencer/gickup/releases/download/v0.9/gickup_0.9_linux_arm64.tar.gz
        dest: /usr/local/bin
        remote_src: true

  roles:
    - stefangweichinger.ansible_rclone

  tasks:
    - name: Install mailutils.
      ansible.builtin.apt:
        name: mailutils
        state: present

    - name: Copy backup scripts into place.
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/pi/{{ item }}"
        mode: 0755
      become: false
      loop:
        - backup.sh
        - gickup.sh

    - name: Create mount point directories.
      ansible.builtin.file:
        path: "/Volumes/{{ item }}"
        state: directory
      loop: "{{ cifs_volumes }}"

    - name: Mount SMB volumes.
      ansible.posix.mount:
        src: "//{{ cifs_server }}/{{ item }}"
        path: "/Volumes/{{ item }}"
        fstype: cifs
        opts: 'uid=pi,mfsymlinks,username={{ cifs_username }},password={{ cifs_password }}'
        state: mounted
      loop: "{{ cifs_volumes }}"

    - name: Add cron job to run backup weekly, at 0300 on Sundays.
      ansible.builtin.cron:
        name: Run backup script.
        minute: "0"
        hour: "3"
        weekday: "0"
        job: /home/pi/backup.sh
        state: present
      become: false

    # - name: Add cron job to run gickup daily, at 0200.
    #   ansible.builtin.cron:
    #     name: Run gickup script.
    #     minute: "0"
    #     hour: "2"
    #     weekday: "0"
    #     job: /home/pi/gickup.sh
    #     state: present
    #   become: false

    # System setup tasks.
    - name: Ensure PoE fans on Pi are set correctly.
      ansible.builtin.blockinfile:
        path: /boot/config.txt
        block: |
          # PoE Hat Fan Speeds
          dtparam=poe_fan_temp0=50000
          dtparam=poe_fan_temp1=60000
          dtparam=poe_fan_temp2=70000
          dtparam=poe_fan_temp3=80000
