---
- name: Install necessary dependencies.
  ansible.builtin.package:
    name: git
    state: present

- name: Create gickup src dir.
  ansible.builtin.file:
    path: /usr/local/src/gickup
    state: directory
    mode: 0755

- name: Clone gickup.
  ansible.builtin.git:
    repo: 'https://github.com/cooperspencer/gickup.git'
    dest: /usr/local/src/gickup
    version: edcf454

- name: Build gickup.
  ansible.builtin.command: /usr/local/go/bin/go build .
  args:
    chdir: /usr/local/src/gickup
    creates: /usr/local/src/gickup/gickup

- name: Symlink gickup into bin dir.
  ansible.builtin.file:
    src: /usr/local/src/gickup/gickup
    dest: /usr/local/bin/gickup
    state: link
